# Generated by Django 3.0.4 on 2020-05-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litmus', '0005_auto_20200508_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
