# Generated by Django 3.0.4 on 2020-05-17 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('litmus', '0008_remove_notes_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
